# Generated by Django 5.0.1 on 2024-05-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='author_pref',
        ),
    ]
