# Generated by Django 5.0.1 on 2024-02-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_pulished',
        ),
    ]
