# Generated by Django 5.0.1 on 2024-02-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='availability',
        ),
    ]
