# Generated by Django 5.0.1 on 2024-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_remove_book_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='upload_status',
        ),
    ]
