# Generated by Django 5.0.1 on 2024-05-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        ('book_management', '0012_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='book_management.book'),
            preserve_default=False,
        ),
    ]
